// Mock product data for static deployment
export const MOCK_PRODUCTS = [
  {
    id: '1',
    slug: 'bpc-157',
    title: 'BPC-157',
    commonName: 'Body Protection Compound',
    description: 'Pentadecapeptide with potential regenerative properties. Research-use only.',
    category: 'PEPTIDES',
    molecularWeight: '1419.55',
    powder: '#FFFFFF',
    featured: true,
    status: 'PUBLISHED',
    imageUrl: '/images/products/bpc-157.png',
    purity: 99.8,
    variations: [
      { id: 'v1', sizeMg: 5, sku: 'BPC-5MG', priceCents: 4800, stockCount: 50, weightG: 0.005 },
      { id: 'v2', sizeMg: 10, sku: 'BPC-10MG', priceCents: 8800, stockCount: 30, weightG: 0.01 },
      { id: 'v3', sizeMg: 20, sku: 'BPC-20MG', priceCents: 15800, stockCount: 20, weightG: 0.02 },
    ],
    coas: [],
  },
  {
    id: '2',
    slug: 'tb-500',
    title: 'TB-500',
    commonName: 'Thymosin Beta-4',
    description: 'Synthetic peptide fragment of thymosin beta-4 with regenerative properties. Research-use only.',
    category: 'PEPTIDES',
    molecularWeight: '4963.49',
    powder: '#F8F8F8',
    featured: true,
    status: 'PUBLISHED',
    imageUrl: '/images/products/tb-500.png',
    purity: 99.5,
    variations: [
      { id: 'v4', sizeMg: 5, sku: 'TB-5MG', priceCents: 5600, stockCount: 40, weightG: 0.005 },
      { id: 'v5', sizeMg: 10, sku: 'TB-10MG', priceCents: 9800, stockCount: 25, weightG: 0.01 },
      { id: 'v6', sizeMg: 20, sku: 'TB-20MG', priceCents: 17800, stockCount: 15, weightG: 0.02 },
    ],
    coas: [],
  },
  {
    id: '3',
    slug: 'sermorelin',
    title: 'Sermorelin',
    commonName: 'GHRH (1-29)',
    description: 'Growth hormone-releasing hormone analogue. Research-use only.',
    category: 'PEPTIDES',
    molecularWeight: '3357.93',
    powder: '#FFFEF8',
    featured: true,
    status: 'PUBLISHED',
    imageUrl: '/images/products/sermorelin.png',
    purity: 99.2,
    variations: [
      { id: 'v7', sizeMg: 2, sku: 'SER-2MG', priceCents: 6800, stockCount: 35, weightG: 0.002 },
      { id: 'v8', sizeMg: 5, sku: 'SER-5MG', priceCents: 14800, stockCount: 20, weightG: 0.005 },
      { id: 'v9', sizeMg: 10, sku: 'SER-10MG', priceCents: 26800, stockCount: 10, weightG: 0.01 },
    ],
    coas: [],
  },
  {
    id: '4',
    slug: 'ipamorelin',
    title: 'Ipamorelin',
    commonName: 'Growth Hormone Secretagogue',
    description: 'Selective growth hormone secretagogue receptor agonist. Research-use only.',
    category: 'PEPTIDES',
    molecularWeight: '711.85',
    powder: '#FFFFFF',
    featured: false,
    status: 'PUBLISHED',
    imageUrl: '/images/products/ipamorelin.png',
    purity: 99.6,
    variations: [
      { id: 'v10', sizeMg: 2, sku: 'IPA-2MG', priceCents: 4200, stockCount: 45, weightG: 0.002 },
      { id: 'v11', sizeMg: 5, sku: 'IPA-5MG', priceCents: 9200, stockCount: 30, weightG: 0.005 },
      { id: 'v12', sizeMg: 10, sku: 'IPA-10MG', priceCents: 16800, stockCount: 18, weightG: 0.01 },
    ],
    coas: [],
  },
  {
    id: '5',
    slug: 'cjc-1295',
    title: 'CJC-1295',
    commonName: 'Modified GHRH',
    description: 'Long-acting growth hormone-releasing hormone analogue. Research-use only.',
    category: 'PEPTIDES',
    molecularWeight: '3647.28',
    powder: '#FAFAFA',
    featured: false,
    status: 'PUBLISHED',
    imageUrl: '/images/products/cjc-1295.png',
    purity: 99.4,
    variations: [
      { id: 'v13', sizeMg: 2, sku: 'CJC-2MG', priceCents: 5800, stockCount: 38, weightG: 0.002 },
      { id: 'v14', sizeMg: 5, sku: 'CJC-5MG', priceCents: 12800, stockCount: 22, weightG: 0.005 },
      { id: 'v15', sizeMg: 10, sku: 'CJC-10MG', priceCents: 23800, stockCount: 12, weightG: 0.01 },
    ],
    coas: [],
  },
  {
    id: '6',
    slug: 'melanotan-2',
    title: 'Melanotan II',
    commonName: 'MT-2',
    description: 'Synthetic analogue of alpha-melanocyte stimulating hormone. Research-use only.',
    category: 'PEPTIDES',
    molecularWeight: '1024.18',
    powder: '#FFF9F0',
    featured: false,
    status: 'PUBLISHED',
    imageUrl: '/images/products/melanotan-2.png',
    purity: 99.7,
    variations: [
      { id: 'v16', sizeMg: 10, sku: 'MT2-10MG', priceCents: 3800, stockCount: 55, weightG: 0.01 },
      { id: 'v17', sizeMg: 20, sku: 'MT2-20MG', priceCents: 6800, stockCount: 35, weightG: 0.02 },
      { id: 'v18', sizeMg: 50, sku: 'MT2-50MG', priceCents: 14800, stockCount: 18, weightG: 0.05 },
    ],
    coas: [],
  },
]
