// Mock product data for static deployment
export const MOCK_PRODUCTS = [
  {
    id: '1',
    slug: 'phosphatidylcholine',
    title: 'Phosphatidylcholine',
    commonName: 'PC / Lecithin',
    description: 'High-purity phosphatidylcholine, a major component of cell membranes. Research-use only.',
    category: 'PHOSPHOLIPIDS',
    molecularWeight: '758.07',
    powder: '#F5F0E8',
    featured: true,
    status: 'PUBLISHED',
    imageUrl: '/images/products/phosphatidylcholine.png',
    purity: 99.5,
    variations: [
      { id: 'v1', sizeMg: 100, sku: 'PC-100MG', priceCents: 4800, stockCount: 50, weightG: 0.1 },
      { id: 'v2', sizeMg: 500, sku: 'PC-500MG', priceCents: 18800, stockCount: 30, weightG: 0.5 },
      { id: 'v3', sizeMg: 1000, sku: 'PC-1G', priceCents: 32800, stockCount: 20, weightG: 1.0 },
    ],
    coas: [],
  },
  {
    id: '2',
    slug: 'phosphatidylserine',
    title: 'Phosphatidylserine',
    commonName: 'PS',
    description: 'Phosphatidylserine is a phospholipid component of cell membranes. Research-use only.',
    category: 'PHOSPHOLIPIDS',
    molecularWeight: '810.01',
    powder: '#F2EDE5',
    featured: true,
    status: 'PUBLISHED',
    imageUrl: '/images/products/phosphatidylserine.png',
    purity: 99.3,
    variations: [
      { id: 'v4', sizeMg: 100, sku: 'PS-100MG', priceCents: 5600, stockCount: 40, weightG: 0.1 },
      { id: 'v5', sizeMg: 500, sku: 'PS-500MG', priceCents: 22800, stockCount: 25, weightG: 0.5 },
      { id: 'v6', sizeMg: 1000, sku: 'PS-1G', priceCents: 39800, stockCount: 15, weightG: 1.0 },
    ],
    coas: [],
  },
  {
    id: '3',
    slug: 'ceramide-c24',
    title: 'Ceramide C24',
    commonName: 'N-Lignoceroylsphingosine',
    description: 'Ceramide C24 is a sphingolipid involved in cell signaling and apoptosis. Research-use only.',
    category: 'CERAMIDES',
    molecularWeight: '649.06',
    powder: '#F8F3EB',
    featured: true,
    status: 'PUBLISHED',
    imageUrl: '/images/products/ceramide-c24.png',
    purity: 99.7,
    variations: [
      { id: 'v7', sizeMg: 50, sku: 'CER24-50MG', priceCents: 6800, stockCount: 35, weightG: 0.05 },
      { id: 'v8', sizeMg: 100, sku: 'CER24-100MG', priceCents: 12800, stockCount: 20, weightG: 0.1 },
      { id: 'v9', sizeMg: 250, sku: 'CER24-250MG', priceCents: 28800, stockCount: 10, weightG: 0.25 },
    ],
    coas: [],
  },
];
